### PR TITLE
Add support for non-ASCII characters in virtual-hyperscript tags

### LINKED ISSUE #249: Non-ASCII symbol blows class parsing
Here’s what happens:

```js
h('.ascii.classes').properties.className
//» 'ascii classes'

h('.classesλwith.unicode»characters').properties.className
//» 'classes unicode'
```

According to [the spec](http://dev.w3.org/csswg/css-syntax/#ident-token-diagram) any non-ascii character can be used in an identifier without escaping. Escaping CSS characters may be a complex topic – but allowing non-ascii symbols should be a breeze.

### PR DESCRIPTION
**Pull request by Mark-Wood**
Fixes #249

### CODE REVIEW

**Comment by Matt-Esch** [comment]
I believe there's a diff somewhere that improves the perf of this in general (removes the regex and split). Merging for now, but you might want to think about back porting for the upcoming patch.

**Comment by neonstalwart** [comment]
> I believe there's a diff somewhere that improves the perf of this in general (removes the regex and split).

i believe it's #180

**Comment by tomekwi** [comment]
@Mark-Wood thanks! :D

**Comment by tomekwi** [comment]
@Matt-Esch @neonstalwart would you be so kind to release this along with other recent patches?

**Pull request merged**
