### PR TITLE
Support NodeJS 0.12

### PR DESCRIPTION
**Pull request by kuraga**

### CODE REVIEW

**Comment by kuraga** [comment]
`io.js` fails: https://travis-ci.org/Matt-Esch/virtual-dom/jobs/57133430
Any ideas about it?

**Comment by kuraga** [comment]
`io.js` fails: https://travis-ci.org/Matt-Esch/virtual-dom/jobs/57133430
Any ideas about it?

**Comment by Matt-Esch** [comment]
This is probably a bug in tap-spec (I've seen the same thing on windows and mac, but never linux). It's something to do with (a)sync writes with console.log vs fs.write(Sync).

Would be good to update tap-spec to latest to see if the bug has been fixed, if not I'd prefer a pr on tap-spec over removing it.

**Comment by jails** [comment]
Should be solved in #225

**Comment by Matt-Esch** [comment]
merged #225

**Pull request closed without merging**
